"""
Pipeline Configuration — Auto-computed from user_config.py
============================================================
Do NOT edit this file. Edit user_config.py instead.

This file reads user_config.py and derives all pipeline
settings automatically — UTM zone, output paths, etc.
"""

from pathlib import Path
import numpy as np

# ─── Read user config ─────────────────────────────────────────
from user_config import (
    AOI_NAME, AOI_COORDS,
    YEAR_HISTORICAL, YEAR_RECENT,
    DATE_HISTORICAL_START, DATE_HISTORICAL_END,
    DATE_RECENT_START, DATE_RECENT_END,
    DRIVE_FOLDER,
)

# ─── Auto-detect UTM zone from AOI centroid ───────────────────
def _get_utm_epsg(coords):
    """Compute correct UTM EPSG from AOI centroid longitude."""
    lons = [c[0] for c in coords]
    lats = [c[1] for c in coords]
    cx   = np.mean(lons)
    cy   = np.mean(lats)
    zone = int((cx + 180) / 6) + 1
    if cy >= 0:
        return f"EPSG:326{zone:02d}"   # Northern hemisphere
    else:
        return f"EPSG:327{zone:02d}"   # Southern hemisphere

TARGET_CRS = _get_utm_epsg(AOI_COORDS)
TARGET_RES = 30   # metres

# ─── Colab paths ──────────────────────────────────────────────
COLAB_ROOT   = Path("/content")
DRIVE_ROOT   = Path("/content/drive/MyDrive") / DRIVE_FOLDER

# All outputs for this AOI go in their own subfolder
PIPELINE_DIR  = COLAB_ROOT / "pipeline_outputs" / AOI_NAME
RAW_DIR       = PIPELINE_DIR / "raw"
LABELS_DIR    = PIPELINE_DIR / "labels"
RASTERS_DIR   = PIPELINE_DIR / "rasters"
MODELS_DIR    = PIPELINE_DIR / "models"
OUTPUTS_DIR   = PIPELINE_DIR / "outputs"
MAPS_DIR      = OUTPUTS_DIR  / "maps"
PREDS_DIR     = OUTPUTS_DIR  / "predictions"
VALID_DIR     = OUTPUTS_DIR  / "validation"

for _d in [RAW_DIR, LABELS_DIR, RASTERS_DIR,
           MODELS_DIR, MAPS_DIR, PREDS_DIR, VALID_DIR]:
    _d.mkdir(parents=True, exist_ok=True)

# ─── Input file paths (downloaded by Stage 0) ─────────────────
LANDSAT_1985_PATH = RAW_DIR / f"{AOI_NAME}_landsat_{YEAR_HISTORICAL}.tif"
LANDSAT_2023_PATH = RAW_DIR / f"{AOI_NAME}_landsat_{YEAR_RECENT}.tif"
GHSL_PATH         = RAW_DIR / f"{AOI_NAME}_GHSL_2020.tif"
GHSL_PATH_1985    = RAW_DIR / f"{AOI_NAME}_GHSL_1985.tif"
ELEVATION_PATH    = RAW_DIR / f"{AOI_NAME}_elevation.tif"
SLOPE_PATH        = RAW_DIR / f"{AOI_NAME}_slope.tif"
DIST_WATER_PATH   = RAW_DIR / f"{AOI_NAME}_distance_to_water.tif"
DIST_URBAN_PATH   = RAW_DIR / f"{AOI_NAME}_distance_to_urban.tif"

# ─── Landsat band names ───────────────────────────────────────
LANDSAT_BANDS_1985 = ["B1", "B2", "B3", "B4", "B5", "B7"]  # L5 TM
LANDSAT_BANDS_2023 = ["B2", "B3", "B4", "B5", "B6", "B7"]  # L8/9 OLI

# ─── GHSL thresholds — computed automatically in Stage 1 ──────
# These are set by Stage 1 after analysing the GHSL time series
# Default fallback values — overwritten by auto-detection
BUILT_THRESHOLD_1985 = 250.0
BUILT_THRESHOLD_2023 = 250.0

# ─── Classifier settings ──────────────────────────────────────
N_ESTIMATORS       = 300
MAX_DEPTH          = 20
TEST_SIZE          = 0.2
RANDOM_STATE       = 42
N_URBAN_SAMPLES    = 8000
N_NONURBAN_SAMPLES = 16000
CLASS_WEIGHT_1985  = {0: 1, 1: 2}
CLASS_WEIGHT_2023  = {0: 1, 1: 3}

# ─── CA-ANN settings ──────────────────────────────────────────
CA_NEIGHBORHOOD   = 3
CA_ITERATIONS     = 10
CA_THRESHOLD      = 0.08
# ANNUAL_RATE is computed automatically from GHSL in Stage 1
ANNUAL_RATE       = None   # set by Stage 1

ANN_HIDDEN_LAYERS = [64, 32]
ANN_EPOCHS        = 100
ANN_LEARNING_RATE = 1e-3
ANN_BATCH_SIZE    = 512

# ─── Visualisation ────────────────────────────────────────────
DPI      = 150
FIG_SIZE = (14, 10)

# ─── Input check ──────────────────────────────────────────────
def check_inputs(verbose=True):
    required = {
        LANDSAT_1985_PATH.name: LANDSAT_1985_PATH,
        LANDSAT_2023_PATH.name: LANDSAT_2023_PATH,
        GHSL_PATH.name:         GHSL_PATH,
        GHSL_PATH_1985.name:    GHSL_PATH_1985,
        ELEVATION_PATH.name:    ELEVATION_PATH,
        SLOPE_PATH.name:        SLOPE_PATH,
        DIST_WATER_PATH.name:   DIST_WATER_PATH,
        DIST_URBAN_PATH.name:   DIST_URBAN_PATH,
    }
    all_ok = True
    if verbose:
        print(f"── Input check for {AOI_NAME} ───────────────────")
    for name, path in required.items():
        exists = path.exists()
        if not exists:
            all_ok = False
        if verbose:
            size = f"{path.stat().st_size/1e6:.1f} MB" if exists else "MISSING"
            print(f"  {'✅' if exists else '❌'} {name:<45} {size}")
    if verbose:
        print("─────────────────────────────────────────────────")
        print("  ✅ All inputs present" if all_ok else
              f"  ❌ Run Stage 0 to download missing files")
    return all_ok


if __name__ == "__main__":
    print(f"AOI:        {AOI_NAME}")
    print(f"UTM zone:   {TARGET_CRS}  (auto-detected)")
    print(f"Output dir: {PIPELINE_DIR}")
    check_inputs()
